### ISSUE TITLE
Permission Denies

### ISSUE THREAD

**Issue by Shamim1977** [fortuna-intelligence/tesseract-lambda#1]
I just changed the test.js file name to index.js and zipped everything and created a lambda function. I am using linux x64 and its always running there. When I run a test, the following message appears in detail-

START RequestId: 7456cbf0-a6eb-11e7-ba22-c5e4ecea99e6 Version: $LATEST
2017-10-01T20:59:47.393Z	7456cbf0-a6eb-11e7-ba22-c5e4ecea99e6	exec error: Error: Command failed: LD_LIBRARY_PATH=./lib TESSDATA_PREFIX=./ ./tesseract test.png stdout -l eng -psm 8
/bin/sh: ./tesseract: Permission denied

END RequestId: 7456cbf0-a6eb-11e7-ba22-c5e4ecea99e6
REPORT RequestId: 7456cbf0-a6eb-11e7-ba22-c5e4ecea99e6	Duration: 223.94 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 22 MB	

Can't figure out what to do. 
Please suggest.

**Comment by rodrigoalviani** [comment]
Did you try `chmod +x tesseract` before zip?

**Comment by Shamim1977** [comment]
Thanks.

**Comment by rodrigoalviani** [comment]
I think we can close #1
